//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/InputActions/TouchManager.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/InputActions/TouchManager.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @TouchManagerAPI: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @TouchManagerAPI()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""TouchManager"",
    ""maps"": [
        {
            ""name"": ""Touch1"",
            ""id"": ""7d8330ad-1c17-46eb-bc55-1f3372ff88f5"",
            ""actions"": [
                {
                    ""name"": ""TouchState"",
                    ""type"": ""Button"",
                    ""id"": ""87be5791-75ff-481f-b6eb-516c1a8d419c"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchPosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5ff2f26c-de0a-4fc1-8a32-9495d25f3a15"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchDelta"",
                    ""type"": ""PassThrough"",
                    ""id"": ""c9914d10-177b-4899-84f0-17ca16845102"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""15fe199b-4714-4708-83bb-71249cdcc38f"",
                    ""path"": ""<Touchscreen>/primaryTouch/press"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""575d8e5d-e042-498d-a840-d1c851d52f52"",
                    ""path"": ""<Touchscreen>/primaryTouch/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""41dff2e1-1bdc-4f8a-8a5b-5b9061c1c3b7"",
                    ""path"": ""<Touchscreen>/primaryTouch/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""Touch2"",
            ""id"": ""05c4e60a-14b2-4ea3-8a12-d35bfa271b36"",
            ""actions"": [
                {
                    ""name"": ""TouchState"",
                    ""type"": ""Button"",
                    ""id"": ""0096255b-d7b8-436c-9dcc-d5338b5146b1"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": ""Press"",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchPosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0265fcbe-ed4c-4648-9d5d-69f80c0e3d0f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TouchDelta"",
                    ""type"": ""PassThrough"",
                    ""id"": ""356a755a-c928-45d8-893c-52cb9445d4e1"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""45ff71c6-8bf0-43b4-aa83-067a9b79d34e"",
                    ""path"": ""<Touchscreen>/touch1/press"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchState"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""09e15caf-7777-4ffb-a9a5-9694f43d7d07"",
                    ""path"": ""<Touchscreen>/touch1/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchPosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""459d514d-c255-4ff0-8e88-4b9dda6e62d3"",
                    ""path"": ""<Touchscreen>/touch1/delta"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TouchDelta"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Touch1
        m_Touch1 = asset.FindActionMap("Touch1", throwIfNotFound: true);
        m_Touch1_TouchState = m_Touch1.FindAction("TouchState", throwIfNotFound: true);
        m_Touch1_TouchPosition = m_Touch1.FindAction("TouchPosition", throwIfNotFound: true);
        m_Touch1_TouchDelta = m_Touch1.FindAction("TouchDelta", throwIfNotFound: true);
        // Touch2
        m_Touch2 = asset.FindActionMap("Touch2", throwIfNotFound: true);
        m_Touch2_TouchState = m_Touch2.FindAction("TouchState", throwIfNotFound: true);
        m_Touch2_TouchPosition = m_Touch2.FindAction("TouchPosition", throwIfNotFound: true);
        m_Touch2_TouchDelta = m_Touch2.FindAction("TouchDelta", throwIfNotFound: true);
    }

    ~@TouchManagerAPI()
    {
        UnityEngine.Debug.Assert(!m_Touch1.enabled, "This will cause a leak and performance issues, TouchManagerAPI.Touch1.Disable() has not been called.");
        UnityEngine.Debug.Assert(!m_Touch2.enabled, "This will cause a leak and performance issues, TouchManagerAPI.Touch2.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Touch1
    private readonly InputActionMap m_Touch1;
    private List<ITouch1Actions> m_Touch1ActionsCallbackInterfaces = new List<ITouch1Actions>();
    private readonly InputAction m_Touch1_TouchState;
    private readonly InputAction m_Touch1_TouchPosition;
    private readonly InputAction m_Touch1_TouchDelta;
    /// <summary>
    /// Provides access to input actions defined in input action map "Touch1".
    /// </summary>
    public struct Touch1Actions
    {
        private @TouchManagerAPI m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public Touch1Actions(@TouchManagerAPI wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Touch1/TouchState".
        /// </summary>
        public InputAction @TouchState => m_Wrapper.m_Touch1_TouchState;
        /// <summary>
        /// Provides access to the underlying input action "Touch1/TouchPosition".
        /// </summary>
        public InputAction @TouchPosition => m_Wrapper.m_Touch1_TouchPosition;
        /// <summary>
        /// Provides access to the underlying input action "Touch1/TouchDelta".
        /// </summary>
        public InputAction @TouchDelta => m_Wrapper.m_Touch1_TouchDelta;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Touch1; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="Touch1Actions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(Touch1Actions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Touch1Actions" />
        public void AddCallbacks(ITouch1Actions instance)
        {
            if (instance == null || m_Wrapper.m_Touch1ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Touch1ActionsCallbackInterfaces.Add(instance);
            @TouchState.started += instance.OnTouchState;
            @TouchState.performed += instance.OnTouchState;
            @TouchState.canceled += instance.OnTouchState;
            @TouchPosition.started += instance.OnTouchPosition;
            @TouchPosition.performed += instance.OnTouchPosition;
            @TouchPosition.canceled += instance.OnTouchPosition;
            @TouchDelta.started += instance.OnTouchDelta;
            @TouchDelta.performed += instance.OnTouchDelta;
            @TouchDelta.canceled += instance.OnTouchDelta;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Touch1Actions" />
        private void UnregisterCallbacks(ITouch1Actions instance)
        {
            @TouchState.started -= instance.OnTouchState;
            @TouchState.performed -= instance.OnTouchState;
            @TouchState.canceled -= instance.OnTouchState;
            @TouchPosition.started -= instance.OnTouchPosition;
            @TouchPosition.performed -= instance.OnTouchPosition;
            @TouchPosition.canceled -= instance.OnTouchPosition;
            @TouchDelta.started -= instance.OnTouchDelta;
            @TouchDelta.performed -= instance.OnTouchDelta;
            @TouchDelta.canceled -= instance.OnTouchDelta;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Touch1Actions.UnregisterCallbacks(ITouch1Actions)" />.
        /// </summary>
        /// <seealso cref="Touch1Actions.UnregisterCallbacks(ITouch1Actions)" />
        public void RemoveCallbacks(ITouch1Actions instance)
        {
            if (m_Wrapper.m_Touch1ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Touch1Actions.AddCallbacks(ITouch1Actions)" />
        /// <seealso cref="Touch1Actions.RemoveCallbacks(ITouch1Actions)" />
        /// <seealso cref="Touch1Actions.UnregisterCallbacks(ITouch1Actions)" />
        public void SetCallbacks(ITouch1Actions instance)
        {
            foreach (var item in m_Wrapper.m_Touch1ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Touch1ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="Touch1Actions" /> instance referencing this action map.
    /// </summary>
    public Touch1Actions @Touch1 => new Touch1Actions(this);

    // Touch2
    private readonly InputActionMap m_Touch2;
    private List<ITouch2Actions> m_Touch2ActionsCallbackInterfaces = new List<ITouch2Actions>();
    private readonly InputAction m_Touch2_TouchState;
    private readonly InputAction m_Touch2_TouchPosition;
    private readonly InputAction m_Touch2_TouchDelta;
    /// <summary>
    /// Provides access to input actions defined in input action map "Touch2".
    /// </summary>
    public struct Touch2Actions
    {
        private @TouchManagerAPI m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public Touch2Actions(@TouchManagerAPI wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Touch2/TouchState".
        /// </summary>
        public InputAction @TouchState => m_Wrapper.m_Touch2_TouchState;
        /// <summary>
        /// Provides access to the underlying input action "Touch2/TouchPosition".
        /// </summary>
        public InputAction @TouchPosition => m_Wrapper.m_Touch2_TouchPosition;
        /// <summary>
        /// Provides access to the underlying input action "Touch2/TouchDelta".
        /// </summary>
        public InputAction @TouchDelta => m_Wrapper.m_Touch2_TouchDelta;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Touch2; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="Touch2Actions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(Touch2Actions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="Touch2Actions" />
        public void AddCallbacks(ITouch2Actions instance)
        {
            if (instance == null || m_Wrapper.m_Touch2ActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_Touch2ActionsCallbackInterfaces.Add(instance);
            @TouchState.started += instance.OnTouchState;
            @TouchState.performed += instance.OnTouchState;
            @TouchState.canceled += instance.OnTouchState;
            @TouchPosition.started += instance.OnTouchPosition;
            @TouchPosition.performed += instance.OnTouchPosition;
            @TouchPosition.canceled += instance.OnTouchPosition;
            @TouchDelta.started += instance.OnTouchDelta;
            @TouchDelta.performed += instance.OnTouchDelta;
            @TouchDelta.canceled += instance.OnTouchDelta;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="Touch2Actions" />
        private void UnregisterCallbacks(ITouch2Actions instance)
        {
            @TouchState.started -= instance.OnTouchState;
            @TouchState.performed -= instance.OnTouchState;
            @TouchState.canceled -= instance.OnTouchState;
            @TouchPosition.started -= instance.OnTouchPosition;
            @TouchPosition.performed -= instance.OnTouchPosition;
            @TouchPosition.canceled -= instance.OnTouchPosition;
            @TouchDelta.started -= instance.OnTouchDelta;
            @TouchDelta.performed -= instance.OnTouchDelta;
            @TouchDelta.canceled -= instance.OnTouchDelta;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="Touch2Actions.UnregisterCallbacks(ITouch2Actions)" />.
        /// </summary>
        /// <seealso cref="Touch2Actions.UnregisterCallbacks(ITouch2Actions)" />
        public void RemoveCallbacks(ITouch2Actions instance)
        {
            if (m_Wrapper.m_Touch2ActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="Touch2Actions.AddCallbacks(ITouch2Actions)" />
        /// <seealso cref="Touch2Actions.RemoveCallbacks(ITouch2Actions)" />
        /// <seealso cref="Touch2Actions.UnregisterCallbacks(ITouch2Actions)" />
        public void SetCallbacks(ITouch2Actions instance)
        {
            foreach (var item in m_Wrapper.m_Touch2ActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_Touch2ActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="Touch2Actions" /> instance referencing this action map.
    /// </summary>
    public Touch2Actions @Touch2 => new Touch2Actions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Touch1" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="Touch1Actions.AddCallbacks(ITouch1Actions)" />
    /// <seealso cref="Touch1Actions.RemoveCallbacks(ITouch1Actions)" />
    public interface ITouch1Actions
    {
        /// <summary>
        /// Method invoked when associated input action "TouchState" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouchState(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TouchPosition" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouchPosition(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TouchDelta" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouchDelta(InputAction.CallbackContext context);
    }
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Touch2" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="Touch2Actions.AddCallbacks(ITouch2Actions)" />
    /// <seealso cref="Touch2Actions.RemoveCallbacks(ITouch2Actions)" />
    public interface ITouch2Actions
    {
        /// <summary>
        /// Method invoked when associated input action "TouchState" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouchState(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TouchPosition" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouchPosition(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TouchDelta" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTouchDelta(InputAction.CallbackContext context);
    }
}
